// export const sideMenuOptions = {
//   module: {
//     ModulePresent:
//     '[\r\n\t\t {\r\n\t\t             \"key\": \"dashboard\",\r\n\t\t             \"navigate\": \"/dashboard\",\r\n\t\t             \"icon\": \"dashboardIcon\",\r\n\t\t             \"title\": \"Dashboard\"\r\n\t\t         },{\r\n\t\t             \"key\": \"importData\",\r\n\t\t             \"navigate\": \"/importdata\",\r\n\t\t             \"icon\": \"importdataIcon\",\r\n\t\t             \"title\": \"Import Data\",\r\n\t\t     \"items\": [\r\n\t\t     {\r\n\t\t                             \"key\": \"importData\",\r\n\t\t                             \"navigate\": \"/importdata\",\r\n\t\t                             \"title\": \"From File\"\r\n\t\t                         }\r\n\t\t     ]\r\n\t\t         }, {\r\n\t\t             \"key\": \"manageAttribute\",\r\n\t\t             \"navigate\": \"/manageAttribute\",\r\n\t\t             \"icon\": \"manageAttribute\",\r\n\t\t             \"title\": \"Manage Attributes\",\r\n\t\t     \"items\": [\r\n\t\t     {\r\n\t\t                             \"key\": \"attributeGroup\",\r\n\t\t                             \"navigate\": \"/attributeGroup\",\r\n\t\t                             \"title\": \"Attribute Group\"\r\n\t\t                         },{\r\n\t\t                             \"key\": \"attribute\",\r\n\t\t                             \"navigate\": \"/attribute\",\r\n\t\t                             \"title\": \"Attribute\"\r\n\t\t                         }\r\n\t\t     ]\r\n\t\t         },{\r\n\t\t             \"key\": \"manageSku\",\r\n\t\t             \"navigate\": \"/skulist\",\r\n\t\t             \"icon\": \"managecatalogIcon\",\r\n\t\t             \"title\": \"Manage Catalogue\"\r\n\t\t         },{\r\n\t\t             \"key\": \"enhancedContent\",\r\n\t\t             \"navigate\": \"/enhancedContent\",\r\n\t\t             \"icon\": \"enhancedContentIcon\",\r\n\t\t             \"title\": \"Enhanced Content\"\r\n\t\t         }\r\n\t\t]',
//   }
// };

// export const sideMenuOptions = {
//   module: {
//     ModulePresent:
//     "[{\"key\":\"dashboard\",\"navigate\":\"/dashboard\",\"icon\":\"dashboardIcon\",\"title\":\"Dashboard\",\"componentId\":\"1\"},{\"key\":\"manageAttribute\",\"navigate\":\"/manageAttribute\",\"icon\":\"manageAttribute\",\"componentId\":\"4\",\"title\":\"Manage Attributes\",\"items\":[{\"key\":\"attributeGroup\",\"navigate\":\"/attributeGroup\",\"title\":\"Attribute Groups\",\"componentId\":\"5\"},{\"key\":\"attribute\",\"navigate\":\"/attribute\",\"title\":\"Attributes\",\"componentId\":\"6\"}]},{\"key\":\"skulist\",\"navigate\":\"/importdata\",\"icon\":\"managecatalogIcon\",\"componentId\":\"2\",\"title\":\"Catalog Management\",\"items\":[{\"key\":\"importData\",\"navigate\":\"/importdata\",\"componentId\":\"3\",\"title\":\"Import Catalog\"},{\"key\":\"skulist\",\"navigate\":\"/skulist\",\"title\":\"Manage Catalog\",\"componentId\":\"7\"}]}, {\r\n\t\t             \"key\": \"assetList\",\r\n\t\t             \"navigate\": \"/assetList\",\r\n\t\t             \"icon\": \"manageAttribute\",\r\n\t\t             \"title\": \"Digital Asset Management\"\r\n\t\t ,\"componentId\":\"43\"        },{\r\n\t\t             \"key\": \"retailerList1\",\r\n\t\t             \"navigate\": \"/retailerlist1\",\r\n\t\t             \"icon\": \"enhancedContentIcon\",\r\n\t\t             \"title\": \"Syndication\"\r\n\t\t ,\"componentId\":\"46\" ,\"items\":[{\"key\":\"retailerAttributeMap\",\"navigate\":\"/retailerAttributeMap\",\"title\":\"Manage Publish Configuration\",\"componentId\":\"46\"},{\"key\":\"retailerList\",\"navigate\":\"/retailerlist\",\"title\":\"Publish Products\",\"componentId\":\"46\"},{\"key\":\"readinessHistory\",\"navigate\":\"/readinessHistory\",\"title\":\"Readiness History\",\"componentId\":\"46\"},{\"key\":\"publishedHistory\",\"navigate\":\"/publishedHistory\",\"title\":\"Publishing History\",\"componentId\":\"46\"}]       },{\"key\":\"superAdmin\",\"navigate\":\"/superAdmin\",\"icon\":\"adminIcon\",\"componentId\":\"22\",\"title\":\"Super Admin\",\"items\":[{\"key\":\"manageUsers\",\"navigate\":\"/manageUsers\",\"componentId\":\"23\",\"title\":\"Manage Users\"},{\"key\":\"manageRoles\",\"navigate\":\"/manageRoles\",\"componentId\":\"24\",\"title\":\"Manage Roles\"}]}\r\n\t\t]"
//   }
// }


export const sideMenuOptions = {
  module: {
    ModulePresent:
"[{\"key\":\"skulist\",\"navigate\":\"/importdata\",\"icon\":\"managecatalogIcon\",\"componentId\":\"2\",\"title\":\"Catalog Management\",\"items\":[{\"key\":\"skulist\",\"navigate\":\"/skulist\",\"title\":\"Manage Catalog\",\"componentId\":\"7\"},{\"key\":\"importData\",\"navigate\":\"/importdata\",\"componentId\":\"3\",\"title\":\"Import Catalog\"}]},{\"key\":\"manageAttribute\",\"navigate\":\"/manageAttribute\",\"icon\":\"manageAttribute\",\"componentId\":\"4\",\"title\":\"Manage Attributes\",\"items\":[{\"key\":\"attributeGroup\",\"navigate\":\"/attributeGroup\",\"title\":\"Attribute Groups\",\"componentId\":\"5\"},{\"key\":\"attribute\",\"navigate\":\"/attribute\",\"title\":\"Attributes\",\"componentId\":\"6\"}]},{\"key\":\"assetList\",\"navigate\":\"/assetList\",\"icon\":\"manageAttribute\",\"title\":\"Digital Asset Management\",\"componentId\":\"43\"},{\"key\":\"retailerList1\",\"navigate\":\"/retailerlist1\",\"icon\":\"enhancedContentIcon\",\"title\":\"Syndication\",\"componentId\":\"46\",\"items\":[{\"key\":\"retailerAttributeMap\",\"navigate\":\"/retailerAttributeMap\",\"title\":\"Manage Publish Configuration\",\"componentId\":\"46\",\"isSecondChildPresent\":true,\"items\":[{\"key\":\"retailerAttributeMap\",\"navigate\":\"/retailerAttributeMap\",\"title\":\"Map Attributes\",\"componentId\":\"46\",\"child\":\"second\"},{\"key\":\"retailersCategoryMapper\",\"navigate\":\"/retailersCategoryMapper\",\"title\":\"Map Retailer Categories\",\"componentId\":\"46\",\"child\":\"second\"}]},{\"key\":\"retailerList\",\"navigate\":\"/retailerlist\",\"title\":\"Publish Products\",\"componentId\":\"46\"},{\"key\":\"readinessHistory\",\"navigate\":\"/readinessHistory\",\"title\":\"Readiness History\",\"componentId\":\"46\"},{\"key\":\"publishedHistory\",\"navigate\":\"/publishedHistory\",\"title\":\"Publishing History\",\"componentId\":\"46\"}]},{\"key\":\"approvalWorkflow\",\"navigate\":\"/approvalWorkflow\",\"icon\":\"pendingApproval\",\"componentId\":\"48\",\"title\":\"Approver Workflow\"},{\"key\":\"superAdmin\",\"navigate\":\"/superAdmin\",\"icon\":\"adminIcon\",\"componentId\":\"22\",\"title\":\"Super Admin\",\"items\":[{\"key\":\"manageUsers\",\"navigate\":\"/manageUsers\",\"componentId\":\"23\",\"title\":\"Manage Users\"},{\"key\":\"manageRoles\",\"navigate\":\"/manageRoles\",\"componentId\":\"24\",\"title\":\"Manage Roles\"}]}]"
  }
}